server:
  port: 8080
  servlet:
    context-path: /certmap

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/certmap?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Xkr11_ku
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

aliPay:
  partner:
  appId:
  privateKey:
  publicKey:
  getaway:
  charset:
  addCoinNotyfyUrl: